### ISSUE TITLE
Eligible countries broadening

### ISSUE THREAD

**Issue by EorgeKit** [mbbu/call_for_bioinfo_internship#1]
I am a graduate student who is highly motivated in becoming a bioinformatician, but unfortunately I come from Tanzania . I would request you to consider including Tanzania as eligible country.
Kind regards

**Comment by kipkurui** [comment]
Thanks for your interest @EorgeKit. Unfortunately, it will only be available for Kenyans for now, given the current situation, and logistical requirements of getting an international intern. Please be on the lookout for the EANBiT MSc program, and H3ABioNet training activities.

**Comment by EorgeKit** [comment]
Received with thanks
